require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

def capacitor_pods
end

target 'App' do
  capacitor_pods
  pod 'Firebase/Messaging', '~> 11.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
